# Generated by Django 3.2.13 on 2023-04-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='quantity_works',
        ),
        migrations.RemoveField(
            model_name='author',
            name='works',
        ),
    ]
